#spring:
#  resources:
#    static-locations: "classpath:/static/"
#
#okta:
#  oauth2:
#    issuer: https://dev-707691.okta.com/oauth2/default
#    client-id: {0oa12sfv1xaU5Hkbi357}
#    client-secret: {ZpkPQkJ5ab2ZJkRhavid7B8sh6_mzGFfkUrgrsC0}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deptstores
    username: root
    password: kingkong
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: true
      show-sql: true